# Generated by Django 6.1.1 on 2026-09-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('immediate', 'Inmediata'), ('2_weeks', '2 semanas'), ('1_month', '1 mes'), ('negotiable', 'Negociable')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_flex',
            field=models.CharField(blank=True, choices=[('remote', 'Remoto'), ('hybrid', 'Hibrido'), ('onsite', 'Presencial')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='search_status',
            field=models.CharField(blank=True, choices=[('active', 'Buscando activamente'), ('passive', 'Abierto a ofertas'), ('not_looking', 'No buscando')], default='', max_length=20),
        ),
    ]
