# Generated by Django 6.1.1 on 2026-09-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('immediate', 'Inmediata'), ('2_weeks', '2 semanas'), ('1_month', '1 mes'), ('negotiable', 'Negociable')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_flex',
            field=models.CharField(blank=True, choices=[('remote', 'Remoto'), ('hybrid', 'Hibrido'), ('onsite', 'Presencial')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_destacado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_profiles', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='search_status',
            field=models.CharField(blank=True, choices=[('active', 'Buscando activamente'), ('passive', 'Abierto a ofertas'), ('not_looking', 'No buscando')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='accounts.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'User Skill',
                'verbose_name_plural': 'User Skills',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
