# Generated by Django 6.1.1 on 2026-09-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_userprofile_availability_userprofile_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
