# Generated by Django 6.1.1 on 2026-09-11 19:24

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_sector_userprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employment_type',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='travel_availability',
            field=models.CharField(blank=True, choices=[('none', 'No'), ('occasional', 'Ocasional'), ('frequent', 'Frecuente')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='willing_to_relocate',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No'), ('somewhere', 'Según destino')], default='', max_length=20),
        ),
    ]
