# Generated by Django 6.1.1 on 2026-09-12 20:38

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_employment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Sector Tag',
                'verbose_name_plural': 'Sector Tags',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sector_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
