# Generated by Django 6.1.1 on 2026-09-14 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sectortag_userprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='willing_to_relocate',
            field=models.CharField(blank=True, choices=[('yes', 'SÃ\xad'), ('no', 'No'), ('somewhere', 'SegÃºn destino')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='SectorRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.sectortag')),
            ],
            options={
                'verbose_name': 'Sector Rol',
                'verbose_name_plural': 'Sector Roles',
                'unique_together': {('sector', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RolEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('sector_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='accounts.sectorrol')),
            ],
            options={
                'verbose_name': 'Rol Especialidad',
                'verbose_name_plural': 'Rol Especialidades',
                'unique_together': {('sector_rol', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('lenguaje', 'Lenguaje'), ('framework', 'Framework'), ('herramienta', 'Herramienta'), ('soft_skill', 'Soft Skill'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='accounts.rolespecialidad')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('must', 'Obligatorio'), ('nice', 'Deseable')], default='nice', max_length=4)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.userprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tag')),
            ],
            options={
                'verbose_name': 'Profile Tag',
                'verbose_name_plural': 'Profile Tags',
                'unique_together': {('profile', 'tag')},
            },
        ),
    ]
