# Generated by Django 6.1.1 on 2026-09-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_willing_to_relocate_sectorrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rolespecialidad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sectorrol'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sectortag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seniority',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('semi_senior', 'Semi-Senior'), ('senior', 'Senior'), ('lead', 'Lead')], default='', max_length=20),
        ),
    ]
