# Generated by Django 6.1.1 on 2026-09-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_especialidad_userprofile_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sector_name',
        ),
    ]
