# Generated by Django 6.1.1 on 2026-09-18 21:01

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sync_title_to_headline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiletag',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='profiletag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('recruiter', 'Reclutador')], default='candidate', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='willing_to_relocate',
            field=models.CharField(blank=True, choices=[('yes', 'Si'), ('no', 'No'), ('somewhere', 'Segun destino')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_description', models.TextField(blank=True, default='')),
                ('company_type', models.CharField(blank=True, choices=[('empresa', 'Empresa'), ('particular', 'Particular')], default='', max_length=20)),
                ('work_modality', models.CharField(blank=True, choices=[('remote', 'Remoto'), ('hybrid', 'Hibrido'), ('onsite', 'Presencial')], default='', max_length=20)),
                ('company_website', models.URLField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('company_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sectortag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter Profile',
                'verbose_name_plural': 'Recruiter Profiles',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=apps.accounts.models.default_list)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('modality', models.CharField(blank=True, choices=[('remote', 'Remoto'), ('hybrid', 'Hibrido'), ('onsite', 'Presencial')], default='', max_length=20)),
                ('salary_range', models.CharField(blank=True, default='', max_length=100)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contrato'), ('freelance', 'Freelance')], default='', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('closed', 'Cerrada'), ('draft', 'Borrador')], default='draft', max_length=20)),
                ('applications_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='accounts.recruiterprofile')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
